version: "3.7"

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      CLIENT_ID: "Reddit client ID"
      CLIENT_SECRET: "Reddit client secret"
      BOT_TOKEN: "Telegram bot token"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7-alpine
